# Generated by Django 3.2.4 on 2021-06-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
